"""empty message

Revision ID: e1c030fdc6a3
Revises: 
Create Date: 2019-10-29 13:59:49.806672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c030fdc6a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_record_username', table_name='record')
    op.create_index(op.f('ix_record_username'), 'record', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_username'), table_name='record')
    op.create_index('ix_record_username', 'record', ['username'], unique=1)
    # ### end Alembic commands ###
